action('none', 'none.py')
action('close', 'close.py')
action('close_auto', 'close_auto.py')
action('generate_qrcode', 'generate_qr.py')
action('echo', 'echo.py')
action('journal', 'show_journals.py')
action('list', 'list.py')
action('pending_feedback', 'pending_feedback.py')
action('report_feedback', 'report_feedback.py')

selector('true', '{"class":"Thing", "attr":"id", "test":"true"}')
selector('list', '{"class":"Failure", "test":"in", "value": "list"}')
selector('journal', '{"class":"Failure", "test":"in", "value": "journal"}')
selector('generate_qr', '{"class":"Failure", "attr":"id", "test":"=", "value": "generate_qr"}')
selector('for-me', '{"class":"SourceUser", "test":"is_concerned"}')
selector('personnal-for-me', '{"class":"Failure", "attr": "id", "test": "=", "value": "personnal-for-me"}')
selector('backoffice', '{"class":"Failure", "test": "in", "value": "top"}')
selector('not-backoffice', '{"class":"Selector", "id": "backoffice", "attr": "is_ok", "test": "false"}')
selector('pending-feedback', '{"class":"Failure", "attr": "id", "test": "=", "value": "pending-feedback"}')
selector('send-pending-feedback', '{"class":"Failure", "attr": "id", "test": "=", "value": "send-pending-feedback"}')
selector('with-pending-feedback', '[1, {"test": "pending_feedback"}, {"class":"Selector", "id": "backoffice", "attr": "is_ok", "test": "false"}]')

user_add('admin', 'thierry.excoffier')
user_add('admin', 'p2205989')

failure_update('top', value='')

failure_update('list', value="Lister :", ask_confirm=False, restricted_to_group_id="admin")
failure_add('top', 'list')
failure_update('list-User', value="les utilisateurs", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-User')
failure_update('list-Failure', value="les pannes", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-Failure')
failure_update('list-Thing', value="les objets", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-Thing')
failure_update('list-Selector', value="les conditions", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-Selector')
failure_update('list-Dispatcher', value="les automatismes", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-Dispatcher')
failure_update('list-Action', value="les actions", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-Action')
failure_update('list-Incident', value="les incidents en cours", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-Incident')

failure_update('journal', value="Afficher journal :", ask_confirm=False, restricted_to_group_id="admin")
failure_add('top', 'journal')
failure_update('journal-config', value="configuration", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('journal', 'journal-config')
failure_update('journal-incident', value="incidents", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('journal', 'journal-incident')

failure_update('misc', value="Divers :", ask_confirm=False, restricted_to_group_id="admin")
failure_add('top', 'misc')
failure_update('pending-feedback', value="Feedbacks de réparation en attente d'envoi", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('misc', 'pending-feedback')
failure_update('send-pending-feedback', value="Envoit le feedback de réparation aux utilisateurs", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('misc', 'send-pending-feedback')

failure_update('generate_qr_top', value='Générer un QR code :', ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.text)
failure_add('top', 'generate_qr_top')
failure_update('generate_qr', value='Entrez le nom d\'une Thing', ask_confirm=True, restricted_to_group_id="admin", display_type=DisplayTypes.input)
failure_add('generate_qr_top', 'generate_qr')

failure_update('personnal', value="Ce qui me concerne :", ask_confirm=False, restricted_to_group_id="admin")
failure_add('top', 'personnal')
failure_update('personnal-for-me', value="Les incidents que je dois traiter", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('personnal', 'personnal-for-me')


thing_update('admin', failure_id="top", comment="Interface d'administration")

dispatcher_update('admin-list', action_id='list', selector_id='list', group_id='admin')
dispatcher_update('admin-journal', action_id='journal', selector_id='journal', group_id='admin')
dispatcher_update('pending-feedback', action_id='echo', selector_id='pending-feedback', incidents="with-pending-feedback")
dispatcher_update('send-pending-feedback', action_id='pending_feedback', selector_id='send-pending-feedback', incidents="with-pending-feedback")
dispatcher_update('generate-qr', action_id='generate_qrcode', selector_id='generate_qr')
dispatcher_update('personnal-for-me', action_id='echo', selector_id='personnal-for-me', incidents="for-me")

# Admin is concerned by all reports. This dis play the reporting feedback
dispatcher_update('report-feedback', action_id='report_feedback', selector_id='not-backoffice', group_id='admin')
# 'z' to be the last dispatched
dispatcher_update('z-backoffice-close', action_id='close_auto', selector_id='backoffice')
