action('none', 'none.py')
action('close', 'close.py')
action('generate_qrcode', 'generate_qr.py')
action('echo', 'echo.py')
action('journal', 'show_journals.py')
action('list', 'list.py')

selector('true', '{"class":"Thing", "attr":"id", "test":"true"}')
selector('list', '{"class":"Failure", "test":"in", "value": "list"}')
selector('journal', '{"class":"Failure", "test":"in", "value": "journal"}')

user_add('admin', 'thierry.excoffier')
user_add('admin', 'p2205989')

failure_update('top', value='')

failure_update('list', value="Lister :", ask_confirm=False, restricted_to_group_id="admin")
failure_add('top', 'list')
failure_update('list-User', value="les utilisateurs", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-User')
failure_update('list-Failure', value="les pannes", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-Failure')
failure_update('list-Thing', value="les objets", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-Thing')
failure_update('list-Selector', value="les conditions", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-Selector')
failure_update('list-Dispatcher', value="les automatismes", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-Dispatcher')
failure_update('list-Action', value="les actions", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-Action')
failure_update('list-Incident', value="les incidents en cours", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('list', 'list-Incident')

failure_update('journal', value="Afficher :", ask_confirm=False, restricted_to_group_id="admin")
failure_add('top', 'journal')
failure_update('journal-config', value="journal de configuration", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('journal', 'journal-config')
failure_update('journal-incident', value="journal des incidents", ask_confirm=False, restricted_to_group_id="admin", display_type=DisplayTypes.button)
failure_add('journal', 'journal-incident')

thing_update('admin', failure_id="top", comment="Interface d'administration")

dispatcher_update('admin-list', action_id='list', selector_id='list')
dispatcher_update('admin-journal', action_id='journal', selector_id='journal')

